### ISSUE TITLE
Support nim 2.0.8

### ISSUE THREAD

**Issue by panno8M** [godot-nim/godotcore#12]

**Comment by insomniacUNDERSCORElemon** [comment]
If this is a hard restriction, it should be part of the install requirements on what exact version should be used. The only thing listed is in the coronation repo and that just says `>= 2.0.0`. 

(note: I had an error during install but it seems unrelated to me, reported in minister repo)

Unless this just means supporting new features or evaluation+other optimization(s)?

-----------------------

Also, the naming scheme here seems a bit obtuse to me. I mean I get it from a contributor standpoint (and maybe for forked versions), but do you expect most users to have a workflow for this? 

Minister seems like it should be the intended usage, and even then I'd probably expect a name like `nim4godot` (there may be some confusion not only with your old repo but also the 3.X pragmagic bindings). For the fully split model, it seems like the `godot` repo could have a more descriptive name (or something more obviously non-user-facing).
